name: 'Push Logs to Elasticsearch'
description: 'A GitHub Action to push workflow logs to Elasticsearch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ELASTICSEARCH_URL }}
    - ${{ inputs.ELASTICSEARCH_INDEX }}
    - ${{ inputs.ELASTICSEARCH_API_KEY_ID }}
    - ${{ inputs.ELASTICSEARCH_API_KEY }}
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GITHUB_REPOSITORY }}
    - ${{ inputs.GITHUB_RUN_ID }}
    - ${{ inputs.GITHUB_PR_NUMBER }}
    - ${{ inputs.GITHUB_PR_TITLE }}
inputs:
  ELASTICSEARCH_URL:
    description: 'Elasticsearch URL'
    required: true
  ELASTICSEARCH_INDEX:
    description: 'Elasticsearch index name'
    required: true
  ELASTICSEARCH_API_KEY_ID:
    description: 'Elasticsearch API Key ID'
    required: true
  ELASTICSEARCH_API_KEY:
    description: 'Elasticsearch API Key'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  GITHUB_REPOSITORY:
    description: 'GitHub repository'
    required: true
  GITHUB_RUN_ID:
    description: 'GitHub run ID'
    required: true
  GITHUB_PR_NUMBER:
    description: 'GitHub PR number'
    required: true
