name: 'Push Logs to Elasticsearch'
description: 'A GitHub Action to push workflow logs to Elasticsearch'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  ELASTICSEARCH_URL:
    description: 'Elasticsearch URL'
    required: true
  ELASTICSEARCH_INDEX:
    description: 'Elasticsearch index name'
    required: true
  ELASTICSEARCH_API_KEY_ID:
    description: 'Elasticsearch API Key ID'
    required: true
  ELASTICSEARCH_API_KEY:
    description: 'Elasticsearch API Key'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  GITHUB_REPOSITORY:
    description: 'GitHub repository'
    required: true
  GITHUB_RUN_ID:
    description: 'GitHub run ID'
    required: true
  GITHUB_PR_NUMBER:
    description: 'GitHub PR number'
    required: true
